7_3 task by celery
thinknetica-django-lab-01/ZusmanOne pull request #71
Opened 2021-02-15 19:56 UTC by ZusmanOne

Closes #56

При создании функции для асинхронной работы, выдается такая ошибка такого рода:Object of type Product is not JSON serializable

2021-02-16 04:21 UTC, mikhailborodin requested changes

2021-02-16 04:21 UTC, mikhailborodin commented on Marketplace/main/views.py
> +        send_celery_mail.delay(instance)
в celery задачи должны передаваться только стерилизуемые объекты: строка, число, словарь и т.д. 
https://www.oddbird.net/2017/03/20/serializing-things/

2021-02-17 07:28 UTC, mikhailborodin requested changes

2021-02-17 07:28 UTC, mikhailborodin commented on Marketplace/main/views.py
> +        task = Product.objects.values('id')
вы передаете все продукты в задачу, а надо только новинки + исправьте сам задачу, у вас там в параметрах Product ожидается

2021-02-17 20:27 UTC, ZusmanOne commented on Marketplace/main/tasks.py
> +def send_celery_mail(Product): #какие параметры должна принимать эта функция?
Не понятно какой параметр следует передавать этой функции или что она должна ожидать....в последствии возникает вопрос с методом delay(на сколько я понимаю он ожидает увидеть тот же параметр...)

2021-02-18 04:37 UTC, mikhailborodin requested changes

2021-02-18 04:37 UTC, mikhailborodin commented on Marketplace/main/tasks.py
> +def send_celery_mail(Product): #какие параметры должна принимать эта функция?
эта функция должна принимать product_id, в ней же выделаете запрос на получений продукта `Product.objects.get(pk=product_id)`

2021-02-18 04:37 UTC, mikhailborodin commented on Marketplace/main/views.py
> +        send_celery_mail.delay(instance.title_product)
здесь вы должны вызывать задачу с product_id `send_celery_mail.delay(instance.product_id)`

2021-02-19 05:55 UTC, mikhailborodin approved these changes

2021-02-20 13:08 UTC, merged